name: Parameter Store Deployment

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'parameter_store/**'

jobs:
  parameter-store:
    name: Deploy Parameter Store
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "parameter_store/pyproject.toml"

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682033488592:role/gh-action-role
          aws-region: us-east-1

      - uses: pulumi/auth-actions@v1
        with:
          organization: Johnyb0223
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:Johnyb0223

      - name: Install the project
        run: uv sync --locked --all-extras
        working-directory: parameter_store

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: johnyb0223/prod
          work-dir: parameter_store
